version: '3'
services:
  chrome:
    build: ./chrome
    cap_add:
      - SYS_ADMIN
    ports:
      - '9222:9222'
  nightwatch:
    build: ./nightwatch
    links:
      - chrome
    volumes:
      - './nightwatch/tests:/tests'
    command: run test-nodemon
