version: '3'
services:
  chrome:
    build: ./chrome
    ports:
      - '9222:9222'
  nightwatch:
    build: ./nightwatch
    links:
      - chrome
    volumes:
      - './nightwatch/tests:/usr/src/app/tests'
    command: run develop
  webdriverio:
    build: ./webdriverio
    links:
      - chrome
    volumes:
      - './webdriverio/specs:/usr/src/app/specs'
    command: run develop
