version: '3'
services:
  chrome:
    build: ./chrome
    ports:
      - '9222:9222'
  nightwatch:
    build: ./nightwatch
    links:
      - chrome
  webdriverio:
    build: ./webdriverio
    links:
      - chrome
