version: '3'
services:
  chrome:
    build: ./chrome
    ports:
      - '9222:9222'
  webdriverio:
    build: ./webdriverio
    links:
      - chrome
    volumes:
      - './webdriverio/specs:/usr/src/app/specs'
    command: run develop
